# Generated by Django 4.1 on 2022-10-25 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GovBenefits',
            fields=[
                ('ben_id', models.AutoField(primary_key=True, serialize=False)),
                ('ben_name', models.TextField()),
                ('ben_description', models.TextField()),
                ('perc_60', models.BooleanField()),
                ('perc_70', models.BooleanField()),
                ('perc_80', models.BooleanField()),
                ('min_grade', models.FloatField()),
                ('min_score', models.IntegerField()),
                ('reg_or_nat_score', models.BooleanField()),
                ('std_test_req', models.BooleanField()),
                ('top_10_perc_req', models.BooleanField()),
                ('academic_progression_peq', models.BooleanField()),
                ('tp_only', models.BooleanField()),
                ('requisite_summary', models.TextField()),
                ('additional', models.TextField()),
            ],
        ),
    ]
