# Generated by Django 4.1.3 on 2022-11-07 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeightedCareer',
            fields=[
                ('weighted_career_id', models.AutoField(primary_key=True, serialize=False)),
                ('demre_code', models.CharField(max_length=15)),
                ('weighted_threshold', models.FloatField()),
                ('unique_code', models.CharField(max_length=15)),
                ('nem_weight', models.PositiveSmallIntegerField()),
                ('ranking_weight', models.PositiveSmallIntegerField()),
                ('math_weight', models.PositiveSmallIntegerField()),
                ('lang_weight', models.PositiveSmallIntegerField()),
                ('hist_weight', models.PositiveSmallIntegerField()),
                ('scie_weight', models.PositiveSmallIntegerField()),
                ('other_weight', models.PositiveSmallIntegerField()),
            ],
        ),
    ]
